### Word Embedding Techniques using Embedding Layer in Keras

In [3]:
### Libraries USed Tensorflow> 2.0  and keras

In [4]:
!pip install tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [5]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [6]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [9]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [10]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [11]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[387, 295, 366, 199], [387, 295, 366, 456], [387, 387, 366, 108], [375, 468, 359, 235, 168], [375, 468, 359, 235, 53], [76, 387, 301, 366, 494], [45, 148, 450, 235]]


### Word Embedding Represntation

In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
import numpy as np

In [14]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 387 295 366 199]
 [  0   0   0   0 387 295 366 456]
 [  0   0   0   0 387 387 366 108]
 [  0   0   0 375 468 359 235 168]
 [  0   0   0 375 468 359 235  53]
 [  0   0   0  76 387 301 366 494]
 [  0   0   0   0  45 148 450 235]]


In [15]:
## 10 feature dimesnions
dim=10


In [16]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [17]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 387, 295, 366, 199], dtype=int32)

In [21]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step


array([[-0.01077695,  0.0192333 , -0.02370924, -0.01835455,  0.03725883,
        -0.00807093, -0.02255693, -0.00046003,  0.02821973, -0.04488833],
       [-0.01077695,  0.0192333 , -0.02370924, -0.01835455,  0.03725883,
        -0.00807093, -0.02255693, -0.00046003,  0.02821973, -0.04488833],
       [-0.01077695,  0.0192333 , -0.02370924, -0.01835455,  0.03725883,
        -0.00807093, -0.02255693, -0.00046003,  0.02821973, -0.04488833],
       [-0.01077695,  0.0192333 , -0.02370924, -0.01835455,  0.03725883,
        -0.00807093, -0.02255693, -0.00046003,  0.02821973, -0.04488833],
       [ 0.01907736, -0.02738391, -0.02493663,  0.03784485, -0.03260492,
         0.02407617, -0.02740175,  0.01126757, -0.03476372,  0.03471129],
       [ 0.01240449, -0.04171995, -0.04437451,  0.02475968,  0.04061694,
        -0.04715407,  0.02053538,  0.0039683 ,  0.04905463,  0.02718088],
       [ 0.00474023,  0.04903075, -0.03488613, -0.04423133, -0.01586338,
        -0.0278441 ,  0.00044   , -0.0199983 

In [24]:
embedded_docs[0]

array([  0,   0,   0,   0, 387, 295, 366, 199], dtype=int32)

In [26]:
print(model.predict(embedded_docs)[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>

In [27]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]